### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by asebak** [Sepia-Officinalis/ecco#1]
Thanks for creating this library, I needed help with creating some code.  What I wanted to do was import a private Ecdsa key using the Nist-256 curve, and then sign the key with data using SHA256.  How would I go about doing this?

**Comment by xcthulhu** [comment]
You could do something like:

```
import static sh.cuttlefi.ecco.CurveParameters.secp256r1;
import sh.cuttlefi.ecco.PrivateKey;

class SignatureExample {
   byte[] signDataExample() {
       PrivateKey privateKey = new PrivateKey(secp256r1, new BigInteger("12345"));
       return privateKey.signUTF8String("message to sign");
   }
}
```

**Comment by asebak** [comment]
Thanks got it working
