### ISSUE TITLE
Negative Private Key

### ISSUE THREAD

**Issue by asebak** [Sepia-Officinalis/ecco#4]
I managed to get this working for one of my private keys for another one of my private key it's negative how but you throw an exeption here:

        if (d.compareTo(BigInteger.ZERO) != 1)
            throw new SecurityException("Private key must be positive.");

to clarify my byte array I am passing is too large, how would I pass a very large byte array to the constructor? Because in java if it's too large it generates a negative number

**Comment by asebak** [comment]
Ok  figured it out I just used the Privatekey.fromByteArray method.

**Comment by xcthulhu** [comment]
> To clarify my byte array I am passing is too large, how would I pass a very large byte array to the constructor? Because in java if it's too large it generates a negative number

The rules are sort of complicated.

If the leading bit of the leading byte of a byte array is 1, then Java will treat the treat the byte array as if it was twos complemented when converting it to a BigInt.

You can get around this by using the `new BigInt(1, byteArray)` constructor which forces the byteArray to be interpreted as unsigned.  This is what `fromByteArray` does.
